remote_theme: "mmistakes/minimal-mistakes@4.27.1"

title: Matt Mleczko

collections:
  pages:
    output: true
    permalink: /:title/
  blog:
    output: true
    permalink: /bettertogether/blog/:title/
  posts: 
    output: true

plugins:
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

# Optional nav config (usually auto-detected, but can force it)
header:
  nav: true

footer:
  links: []

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      nav_exclude: true

  - scope:
      path: "index.md"  # adjust this if your homepage file has a different name or location
      type: pages
    values:
      sidebar:
        image: /assets/images/Mleczko_headshot_cr.jpg
        info:
          title: Assistant Professor, Department of Political Science
          employer: Marquette University 
          email: matthew.mleczko@marquette.edu

sass:
  style: compressed
  load_paths:
    - _sass




